apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: authentik
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["authentik-secret-key"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: authentik
  name: secret-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: authentik
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

