apiVersion: chaos-mesh.org/v1alpha1
kind: BlockChaos
metadata:
  name: hostpath-example-delay
spec:
  selector:
    labelSelectors:
      app: springkube-k8s
  mode: all
  volumeName: hostpath-example
  action: delay
  delay:
    latency: 100s
