apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
  namespace: bank-of-anthos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactionhistory
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

