# cat network-latency.yaml 
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency
    # namespace: bank-of-anthos
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: ledgerwriter
  delay:
    latency: "10000ms"  # 10 seconds of latency 
    correlation: "100"  # Apply delay with 100% correlation to ensure all requests are affected
    jitter: "0ms"
  duration: "300000ms" # latency persists for 5 minutes
